<?php
declare(strict_types=1);
require __DIR__.'/../dkp/auth.php';
require __DIR__.'/../dkp/remember_login.php';
$db=new PDO('sqlite::memory:');$db->exec('PRAGMA foreign_keys=ON');
$db->exec("CREATE TABLE dkp_users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,nickname TEXT,password_hash TEXT,role TEXT,verified_at INTEGER,session_version INTEGER);
CREATE TABLE dkp_tokens(token_hash TEXT PRIMARY KEY,user_id INTEGER REFERENCES dkp_users(id) ON DELETE CASCADE,purpose TEXT,expires_at INTEGER);
CREATE TABLE fc_write_lock(id INTEGER PRIMARY KEY,revision INTEGER);INSERT INTO fc_write_lock VALUES(1,0);
CREATE TABLE fc_registration_members(web_user_id INTEGER PRIMARY KEY,nickname TEXT,status TEXT);");
$mail=[];$auth=new Auth($db,'https://example.test',function($to,$subject,$body)use(&$mail){preg_match('/token=([a-f0-9]{64})/',$body,$m);$mail[]=$m[1];return true;});
$remember=new RememberLogin($auth);$n=0;
function check(bool $ok,string $label):void {global $n;if(!$ok)throw new RuntimeException($label);$n++;}
function denied(Closure $fn):void {try{$fn();}catch(AuthError){check(true,'denied');return;}throw new RuntimeException('Expected denial');}
$password='remember-fixture-password';$hash=Auth::hashPassword($password);
$auth->query('INSERT INTO dkp_users VALUES(1,?,?,?,?,?,1)',['one@example.test','One',$hash,'member',time()]);
$auth->query('INSERT INTO dkp_users VALUES(2,?,?,?,?,NULL,1)',['two@example.test','Two',$hash,'member']);
$user=$auth->login('one@example.test',$password);$first=$remember->issue($user);$second=$remember->issue($user);
check($first['raw']!==$second['raw'],'independent devices');
check($first['expires']>=time()+30*86400-2 && $first['expires']<=time()+30*86400,'30-day fixed expiry');
check(!$auth->query('SELECT 1 FROM dkp_tokens WHERE token_hash=?',[$first['raw']])->fetchColumn(),'raw secret absent from database');
check($remember->fromCookie($first['raw'])['user']['id']===1,'cookie restores correct account');
check($remember->fromCookie($first['hash'])===false,'database hash cannot be used as a browser credential');
foreach([null,[],42,'',str_repeat('a',63),str_repeat('a',65),str_repeat('A',64),str_repeat('f',64)] as $bad)check($remember->fromCookie($bad)===false,'malformed or unknown cookie denied');
denied(fn()=>$remember->issue($auth->user(2)));
denied(fn()=>$auth->token($first['raw'],'reset'));
denied(fn()=>$auth->token($first['raw'],'verify'));
$auth->sendToken(1,'one@example.test','reset');$reset=end($mail);
check($remember->fromCookie($reset)===false,'reset token cannot sign in');
$remember->revokeCookie($reset);check((bool)$auth->token($reset,'reset'),'remember revocation preserves reset tokens');
$auth->query('UPDATE dkp_tokens SET expires_at=? WHERE token_hash=?',[time()+90,$first['hash']]);
$before=(int)$auth->query('SELECT expires_at FROM dkp_tokens WHERE token_hash=?',[$first['hash']])->fetchColumn();
$remember->fromCookie($first['raw']);$remember->fromCookie($first['raw']);
check((int)$auth->query('SELECT expires_at FROM dkp_tokens WHERE token_hash=?',[$first['hash']])->fetchColumn()===$before,'visits do not extend expiry');
$remember->revokeCookie($first['raw']);
check($remember->fromCookie($first['raw'])===false && $remember->byHash($first['hash'])===false,'logout revokes cookie and derived sessions');
check((bool)$remember->fromCookie($second['raw']),'other device stays signed in');
$third=$remember->issue($user,$second['raw'],$second['hash']);
check($remember->fromCookie($second['raw'])===false && (bool)$remember->fromCookie($third['raw']),'new password login replaces current browser token');
$db->exec("CREATE TRIGGER fail_issue BEFORE INSERT ON dkp_tokens BEGIN SELECT RAISE(ABORT,'fixture failure'); END");
try{$remember->issue($user,$third['raw'],$third['hash']);throw new RuntimeException('Missing error');}catch(PDOException){check(true,'write failure propagated');}
check((bool)$remember->fromCookie($third['raw']),'failed replacement preserves previous login');
$db->exec('DROP TRIGGER fail_issue');
$auth->query('UPDATE dkp_users SET verified_at=NULL WHERE id=1');check($remember->fromCookie($third['raw'])===false,'unverified account cannot restore');
$auth->query("UPDATE dkp_users SET verified_at=?,role='officer',session_version=2 WHERE id=1",[time()]);
check($remember->fromCookie($third['raw'])===false,'role/session version change revokes saved login');
denied(fn()=>$remember->issue($user));
$user=$auth->user(1);$fourth=$remember->issue($user);
check($remember->fromCookie($fourth['raw'])['user']['role']==='officer','current role loaded from database');
$auth->query('UPDATE dkp_tokens SET expires_at=? WHERE token_hash=?',[time(),$fourth['hash']]);
check($remember->fromCookie($fourth['raw'])===false && $remember->byHash($fourth['hash'])===false,'expired grant cannot restore or keep a session');
$a=$remember->issue($user);$b=$remember->issue($user);
$auth->changePassword(1,$password,'changed-fixture-password');
check($remember->fromCookie($a['raw'])===false && $remember->fromCookie($b['raw'])===false,'password change revokes all devices');
check((int)$auth->query('SELECT COUNT(*) FROM dkp_tokens WHERE user_id=1')->fetchColumn()===0,'password change removes grants');
$user=$auth->login('one@example.test','changed-fixture-password');$a=$remember->issue($user);$b=$remember->issue($user);
$auth->sendToken(1,'one@example.test','reset');$reset=end($mail);$auth->redeem($reset,'reset',$password);
check($remember->fromCookie($a['raw'])===false && $remember->fromCookie($b['raw'])===false,'email reset revokes all devices');
check((bool)$auth->login('one@example.test',$password),'reset password works');
$user=$auth->user(1);$a=$remember->issue($user);$auth->query('DELETE FROM dkp_users WHERE id=1');
check($remember->fromCookie($a['raw'])===false,'deleted account cannot restore');
echo "$n remember-login checks passed\n";
